### PR TITLE
Allow base-4.17 for GHC 9.2.1

### PR DESCRIPTION
**Pull request by andreasabel**
Allow base-4.17 for GHC 9.2.1, include 9.2.1 in the CI.

The base bump can be done as a hackage revision (without the need to upload a new version).

Blocking:
- BNFC (https://github.com/BNFC/bnfc/issues/398)

### CODE REVIEW

**Comment by maoe** [comment]
Tyhan

**Comment by maoe** [comment]
Thanks! Waiting for CI to finish.

**Comment by maoe** [comment]
Uploaded https://hackage.haskell.org/package/lifted-async-0.10.2.2

**Comment by andreasabel** [comment]
Great!
Probably you also meant to push tag `v0.10.2.2` (missing atm).

**Comment by maoe** [comment]
Ah yes, I forgot to do it. Now it's pushed.

**Pull request merged**
