### PR TITLE
Add mapConcurrently_ and forConcurrently_

### PR DESCRIPTION
**Pull request by sergv**
These functions are present in `async` package and are useful when return value is not important.

### CODE REVIEW

**Comment by maoe** [comment]
Thank you for contributing! It seems that there are build failures for GHC 7.6.3 and 7.8.4. I'm fine to drop support for 7.6.3 but could we make a fix for 7.8.4?

**Comment by sergv** [comment]
@maoe Sure, I've fixed both 7.8.4 and 7.6.3.

**Comment by maoe** [comment]
Perfect! I'll merge this and cut a new release.

**Comment by maoe** [comment]
Just released v0.9.1. Thank you again.

**Comment by sergv** [comment]
Thanks for quick turnaround!

**Pull request merged**
